---
 - name: Including TomcatJenkins Play
   include: jenkins.yml
   when: (groups[target][2] != inventory_hostname)

 - name: Including Nginx Play
   include: nginx.yml
   when: (groups[target][2] == inventory_hostname)

